language: go

os:
  - linux
  - osx
  - windows

go:
  - tip
  - 1.13.x
  - 1.11.x

script:
  - GO111MODULE=on go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
